# Generated by Django 3.2.9 on 2022-03-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
